spring:
  application:
    name: brokerage
  h2:
    console:
      enabled: true 
      path: /h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:file:./data/brokeragedb;;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=false
    initialization-mode: always
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

server:
  error:
    include-message: always
